name: 'Label Actions'

on:
  discussion:
    types: [created]

permissions:
  discussions: write

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh discussion edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.discussion.number }}
          LABELS: solved
