name: 'Label Actions'

on:
  discussion:
    types: [created]

permissions:
  discussions: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository contents
        uses: actions/checkout@v2
      
      - name: Print working directory
        run: pwd

      - name: List directory contents
        run: ls -al
        
      - uses: dessant/label-actions@v4
        with:
          github-token: ${{ github.token }}
          config-path: '.github/label-actions.yml'
          process-only: 'discussions'
