name: Label new discussion

on:
  discussion:
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Label the discussion
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        DISCUSSION_ID=$(jq -r .discussion.node_id "$GITHUB_EVENT_PATH")
        curl -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"labels":["question", "documentation"]}' \
          "https://api.github.com/graphql" \
          -d '{"query":"mutation { addLabelsToLabelable(input:{labelableId:\"'"$DISCUSSION_ID"'\",labelIds:[\"MDU6TGFiZWwyOTkyMzQ1NjY0\"]}) { clientMutationId } }"}'
